### ISSUE TITLE
```python setup.py install``` does not help

### ISSUE THREAD

**Issue by patel-zeel** [minitorch/Module-0#15]
After completing the assignment, I tried to install the package with:
```python
python setup.py install
```

I could import the package at path ```~/Module-0/``` but not anywhere else. What am I doing wrong?

**Comment by srush** [comment]
We recommend `pip install -Ue .` that installs and keeps a symlink as you make changes.

**Comment by patel-zeel** [comment]
That works! Thanks a lot, @srush.
