### ISSUE TITLE
Add argument parser to run tests script

### ISSUE THREAD

**Issue by azpoliak** [minitorch/Module-0#2]
Would it make sense to add argparser to the [run_tests.py](https://github.com/minitorch/Module-0/blob/fb76a2699a2b173e49647c39bf9249b9182e5c18/run_tests.py) scripts so that typing ``python run_tests.py --help`` will give the user more instructions and make it easier to run specific tests instead of all in the module?

**Comment by azpoliak** [comment]
Including that might be redundant because of `pytests` already

**Comment by srush** [comment]
Hmm, yeah. Maybe I should just remove `run_tests.py`?  it's just a very thin auto-generated wrapper on pytest. You can run `python -m pytest -h` and get access to all its options.

**Comment by azpoliak** [comment]
I think its good to have some sort of wrapper like `run_tests.py` that
students can easily run after implement a few of the functions in a task.

**Comment by srush** [comment]
Going to drop this for now. If that class gets another argument I will switch to argparser
