### ISSUE TITLE
The `sum` function tests against itself.

### ISSUE THREAD

**Issue by EteimZ** [minitorch/Module-0#27]
This test case at [line 180](https://github.com/minitorch/Module-0/blob/master/tests/test_operators.py#L180) of [test_operators.py](https://github.com/minitorch/Module-0/blob/master/tests/test_operators.py) tests the `sum` function against itself. The sum function is imported from [operators.py](https://github.com/minitorch/Module-0/blob/master/minitorch/operators.py) and no longer bound to the builtin `sum` function.

```python
@pytest.mark.task0_3
@given(lists(small_floats))
def test_sum(ls: List[float]) -> None:
    assert_close(sum(ls), sum(ls))
```

**Comment by srush** [comment]
Thx. fixed now.
