### ISSUE TITLE
lt should be renamed to gt or the description should be updated

### ISSUE THREAD

**Issue by rezasjourney** [minitorch/Module-0#3]
This function should probably be named `gt` and the math should say `f(x, y)` instead of `f(x)`

https://github.com/minitorch/Module-0/blob/fb76a2699a2b173e49647c39bf9249b9182e5c18/minitorch/operators.py#L31-L34

**Comment by vbartle** [comment]
Can also maybe add a second function named gt and change the description for lt? I think torch has both.

**Comment by srush** [comment]
This is fixed in the main code base. I will push a new version. 

Also there is a GT when you get to the next module https://github.com/minitorch/Module-1/blob/master/minitorch/scalar.py#L68

**Comment by srush** [comment]
(Fixed)
