### ISSUE TITLE
Change Numba version and add Python version

### ISSUE THREAD

**Issue by chiffonng** [minitorch/Module-0#30]
This template requires
- Python 3.8 or higher
- numba == 0.55 in `requirements.txt`

However, there is no matching version for `numba == 0.55` and I had to install the closest version, 0.56 instead. It requires Python < 3.11 that I used for virtual environment. 

This should change to
- Python > 3.8, Python < 3.11
- numba == 0.56 in `requirements.txt`

**Comment by srush** [comment]
fixed for this years version.
