### ISSUE TITLE
AttributeError: module 'minitorch' has no attribute 'is_close'

### ISSUE THREAD

**Issue by helle253** [minitorch/Module-0#36]
Just forked this repo, and ran into an issue where this line change causes tests to fail, even though `is_close` is implemented properly (in the `operators` module)

> E       AttributeError: module 'minitorch' has no attribute 'is_close'
> E       Falsifying example: test_same_as_python(
> E           y=0.0, x=0.0,
> E       )

[The change was just introduced in this commit](https://github.com/minitorch/Module-0/commit/e2aba9c7c1c0b8fdfa99bb78f9b45acee3cf3480) a few days ago.

Updating tests/strategies.py#17 from
```python
assert minitorch.is_close(a, b), "Failure x=%f y=%f" % (a, b)
```

back to

```python
assert minitorch.operators.is_close(a, b), "Failure x=%f y=%f" % (a, b)
```

appears to resolve the issue for me.

**Comment by srush** [comment]
Fixed in the new 2024 version.
