### ISSUE TITLE
(doc) typo and suggestions

### ISSUE THREAD

**Issue by qlibp** [minitorch/Module-0#4]
1. [Seems that it should not be called 'ancestor', in the context of a tree data structure. IMO, it should be a typo](https://github.com/minitorch/Module-0/blob/fb76a2699a2b173e49647c39bf9249b9182e5c18/minitorch/module.py#L35)

2. Besides, the implementation of `named_parameters` should have a clearer description on how to reference the child parameters. I need to dive into the testing code to find out what exactly you want me to do.

3. Also, the final example [here](https://minitorch.github.io/modules.html) doesn't match the photo.

Anyway, thanks for the tutorial, it does help!!!

**Comment by srush** [comment]
Thanks! These are all great comments and I fixed them in the repo. (If you send me your name I will add you to acknowledgements. )
