### ISSUE TITLE
datasets.py should have an import for “import matplotlib.pyplot as plt” 

### ISSUE THREAD

**Issue by vbartle** [minitorch/Module-0#5]
datasets.py should have an import for “import matplotlib.pyplot as plt” at the top of it, because the assignment asks for images to be saved for readme viewing, and the saving mechanism is commented out on line 65 (presumably intentionally or as a hint) as “plt.savefig”. Or at least the import should also be commented out, or the commented plt.savefig should be deleted?

**Comment by srush** [comment]
You can save the image directly from the Visdom UI. You only need to plt if that doesn't work.

**Comment by vbartle** [comment]
Oh okay, so is line 65 unnecessary or left in as a hint?

**Comment by srush** [comment]
Just debugging that got left in. But I will remove.
